[phases.setup]
nixPkgs = ["php82", "nodejs", "composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PHP_EXTENSIONS = "pdo_mysql mysqli"